### ISSUE TITLE
Separate the Slack class from the project

### ISSUE THREAD

**Issue by surafelfikru** [iCog-Labs-Dev/semantic-search-engine#6]
**Problem**
We need to separate the importing of the Slack data logic from the application. there are numerous reasons for this. But the major one is being cohesive. the semantic search engine should be responsible for only just for that. it should have an interface for importing large amounts of data but should also be limited to that. 

let me give you a scenario where this might be a problem. the replatforming_slack team said that they are considering to propose this project as plugin for the mattermost team. if this code goes to the mattermost team the first thing they will be asking is why is there a  slack package? 

Importing slack is done only once and the usecase is limited to a single user.

**Solution** 
As i said on issue #4 we can implement a logic to import large amounts of data on the SemanticSearch class and separately feed this method from another script.

**Comment by TollanBerhanu** [comment]
Already separated
